image: docker:latest
services:
  - docker:19.03.0-dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  

stages:
  - build
  - package
 

build email service:
  image: maven:latest
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar

create container:
  stage: package
  script:
    - docker build -t repository.walnut-it.com/walnut-email-service .
    - docker push repository.walnut-it.com/walnut-email-service
     
  