image: docker:19
#services:
#  - docker:19.03.13-dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - package
 

build email service:
  image: maven:latest
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar

create container:
  stage: package
  script:
    - docker build -t repository.walnut-it.com/walnut-email-service .
    - docker push repository.walnut-it.com/walnut-email-service
     
  